### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jbull477/tc-359-project11#1]
This looks very good except for some hard-tabs I see [here](https://github.com/jbull477/tc-359-project11/blob/master/app/views/layouts/application.html.erb#L11) and [here](https://github.com/jbull477/tc-359-project11/blob/master/app/assets/stylesheets/static.scss#L4-L12) that I'd like you to fix. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by jbull477** [comment]
This should be fixed now.

**Comment by chrisvfritz** [comment]
Much better and _almost_ correct. [This line](https://github.com/jbull477/tc-359-project11/blob/master/app/views/layouts/application.html.erb#L11) still looks inconsistently indented. It's using spaces, but it's not in line with the closing `</ul>`.

**Comment by jbull477** [comment]
Let me know what you think now.

**Comment by chrisvfritz** [comment]
:+1: Marvelous!
